export const AppConfig = {
  site_name: 'FTDS',
  title: 'FTU-Conference',
  description: 'Starter code for your Nextjs Boilerplate with Tailwind CSS',
  locale: 'en',
  text_primary_color: 'text-gray-200',
  text_primary_color_dark: 'text-indigo-900',
  text_secondary_color: 'text-blue-200',
  text_secondary_color_dark: 'text-indigo-900',
  bg_light: 'bg-gray-200',
  bg_dark: 'bg-blue-900',
  border_dark: 'border-blue-900',
  border_light: 'border-gray-200',
  bg_dark_nav: 'bg-indigo-900',
  background_color: '#222',
};
